/*
 * This file is generated by jOOQ.
 */
package com.elasticsearch.engine.demo.domain.mysql.jooq.generator;


import com.elasticsearch.engine.demo.domain.mysql.jooq.generator.tables.Person;
import com.elasticsearch.engine.demo.domain.mysql.jooq.generator.tables.PersonExtend;
import com.elasticsearch.engine.demo.domain.mysql.jooq.generator.tables.records.PersonExtendRecord;
import com.elasticsearch.engine.demo.domain.mysql.jooq.generator.tables.records.PersonRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import org.jooq.types.ULong;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>user</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<PersonRecord, ULong> IDENTITY_PERSON = Identities0.IDENTITY_PERSON;
    public static final Identity<PersonExtendRecord, ULong> IDENTITY_PERSON_EXTEND = Identities0.IDENTITY_PERSON_EXTEND;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PersonRecord> KEY_PERSON_PRIMARY = UniqueKeys0.KEY_PERSON_PRIMARY;
    public static final UniqueKey<PersonRecord> KEY_PERSON_UK_PERSON_NO = UniqueKeys0.KEY_PERSON_UK_PERSON_NO;
    public static final UniqueKey<PersonExtendRecord> KEY_PERSON_EXTEND_PRIMARY = UniqueKeys0.KEY_PERSON_EXTEND_PRIMARY;
    public static final UniqueKey<PersonExtendRecord> KEY_PERSON_EXTEND_UK_PERSON_NO = UniqueKeys0.KEY_PERSON_EXTEND_UK_PERSON_NO;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<PersonRecord, ULong> IDENTITY_PERSON = Internal.createIdentity(Person.PERSON, Person.PERSON.ID);
        public static Identity<PersonExtendRecord, ULong> IDENTITY_PERSON_EXTEND = Internal.createIdentity(PersonExtend.PERSON_EXTEND, PersonExtend.PERSON_EXTEND.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<PersonRecord> KEY_PERSON_PRIMARY = Internal.createUniqueKey(Person.PERSON, "KEY_person_PRIMARY", Person.PERSON.ID);
        public static final UniqueKey<PersonRecord> KEY_PERSON_UK_PERSON_NO = Internal.createUniqueKey(Person.PERSON, "KEY_person_uk_person_no", Person.PERSON.PERSON_NO);
        public static final UniqueKey<PersonExtendRecord> KEY_PERSON_EXTEND_PRIMARY = Internal.createUniqueKey(PersonExtend.PERSON_EXTEND, "KEY_person_extend_PRIMARY", PersonExtend.PERSON_EXTEND.ID);
        public static final UniqueKey<PersonExtendRecord> KEY_PERSON_EXTEND_UK_PERSON_NO = Internal.createUniqueKey(PersonExtend.PERSON_EXTEND, "KEY_person_extend_uk_person_no", PersonExtend.PERSON_EXTEND.PERSON_NO);
    }
}
