/*
 * This file is generated by jOOQ.
 */
package com.elasticsearch.engine.demo.domain.mysql.jooq.generator;


import com.elasticsearch.engine.demo.domain.mysql.jooq.generator.tables.Person;
import com.elasticsearch.engine.demo.domain.mysql.jooq.generator.tables.PersonExtend;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in user
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 人员表
     */
    public static final Person PERSON = Person.PERSON;

    /**
     * 人员扩展表
     */
    public static final PersonExtend PERSON_EXTEND = PersonExtend.PERSON_EXTEND;
}
