/*
 * This file is generated by jOOQ.
 */
package com.elasticsearch.engine.demo.domain.mysql.jooq.generator.tables.records;


import com.elasticsearch.engine.demo.domain.mysql.jooq.generator.tables.PersonExtend;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;

import javax.annotation.Generated;
import java.time.LocalDateTime;


/**
 * 人员扩展表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonExtendRecord extends UpdatableRecordImpl<PersonExtendRecord> implements Record5<ULong, String, String, String, LocalDateTime> {

    private static final long serialVersionUID = 1465944504;

    /**
     * Setter for <code>user.person_extend.id</code>. 自增id
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>user.person_extend.id</code>. 自增id
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>user.person_extend.person_no</code>. 用户编码
     */
    public void setPersonNo(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>user.person_extend.person_no</code>. 用户编码
     */
    public String getPersonNo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>user.person_extend.mail</code>. 邮箱
     */
    public void setMail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>user.person_extend.mail</code>. 邮箱
     */
    public String getMail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>user.person_extend.hobby</code>. 爱好
     */
    public void setHobby(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>user.person_extend.hobby</code>. 爱好
     */
    public String getHobby() {
        return (String) get(3);
    }

    /**
     * Setter for <code>user.person_extend.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>user.person_extend.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<ULong, String, String, String, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<ULong, String, String, String, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return PersonExtend.PERSON_EXTEND.ID;
    }

    @Override
    public Field<String> field2() {
        return PersonExtend.PERSON_EXTEND.PERSON_NO;
    }

    @Override
    public Field<String> field3() {
        return PersonExtend.PERSON_EXTEND.MAIL;
    }

    @Override
    public Field<String> field4() {
        return PersonExtend.PERSON_EXTEND.HOBBY;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return PersonExtend.PERSON_EXTEND.CREATE_TIME;
    }

    @Override
    public ULong component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getPersonNo();
    }

    @Override
    public String component3() {
        return getMail();
    }

    @Override
    public String component4() {
        return getHobby();
    }

    @Override
    public LocalDateTime component5() {
        return getCreateTime();
    }

    @Override
    public ULong value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getPersonNo();
    }

    @Override
    public String value3() {
        return getMail();
    }

    @Override
    public String value4() {
        return getHobby();
    }

    @Override
    public LocalDateTime value5() {
        return getCreateTime();
    }

    @Override
    public PersonExtendRecord value1(ULong value) {
        setId(value);
        return this;
    }

    @Override
    public PersonExtendRecord value2(String value) {
        setPersonNo(value);
        return this;
    }

    @Override
    public PersonExtendRecord value3(String value) {
        setMail(value);
        return this;
    }

    @Override
    public PersonExtendRecord value4(String value) {
        setHobby(value);
        return this;
    }

    @Override
    public PersonExtendRecord value5(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public PersonExtendRecord values(ULong value1, String value2, String value3, String value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PersonExtendRecord
     */
    public PersonExtendRecord() {
        super(PersonExtend.PERSON_EXTEND);
    }

    /**
     * Create a detached, initialised PersonExtendRecord
     */
    public PersonExtendRecord(ULong id, String personNo, String mail, String hobby, LocalDateTime createTime) {
        super(PersonExtend.PERSON_EXTEND);

        set(0, id);
        set(1, personNo);
        set(2, mail);
        set(3, hobby);
        set(4, createTime);
    }
}
